[2024-07-19T11:25:59.307+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T11:25:59.319+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T11:25:59.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T11:25:59.325+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-19T11:25:59.420+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-07-18 00:00:00+00:00
[2024-07-19T11:25:59.425+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=324) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T11:25:59.426+0000] {standard_task_runner.py:64} INFO - Started process 333 to run task
[2024-07-19T11:25:59.426+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_training', 'train_model', 'scheduled__2024-07-18T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/model_train_dag.py', '--cfg-path', '/tmp/tmpb5sc1g37']
[2024-07-19T11:25:59.428+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask train_model
[2024-07-19T11:25:59.463+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [running]> on host 6e10856c4017
[2024-07-19T11:25:59.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random_forest_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:00+00:00'
[2024-07-19T11:25:59.503+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T11:25:59.511+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T11:25:59.512+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/model_train_dag.py", line 16, in train_model
    data = pd.read_csv('/path/to/data/data_clean.csv', delimiter=',', decimal='.')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/data/data_clean.csv'
[2024-07-19T11:25:59.517+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_forest_training, task_id=train_model, run_id=scheduled__2024-07-18T00:00:00+00:00, execution_date=20240718T000000, start_date=20240719T112559, end_date=20240719T112559
[2024-07-19T11:25:59.523+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task train_model ([Errno 2] No such file or directory: '/path/to/data/data_clean.csv'; 333)
[2024-07-19T11:25:59.569+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-19T11:25:59.579+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T11:25:59.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-19T11:36:53.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T11:36:54.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T11:36:54.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T11:36:54.019+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-19T11:36:54.117+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-07-18 00:00:00+00:00
[2024-07-19T11:36:54.128+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=652) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T11:36:54.130+0000] {standard_task_runner.py:64} INFO - Started process 668 to run task
[2024-07-19T11:36:54.130+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_training', 'train_model', 'scheduled__2024-07-18T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/model_train_dag.py', '--cfg-path', '/tmp/tmpbkkkfqf9']
[2024-07-19T11:36:54.132+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask train_model
[2024-07-19T11:36:54.160+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [running]> on host 6e10856c4017
[2024-07-19T11:36:54.218+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random_forest_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:00+00:00'
[2024-07-19T11:36:54.219+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T11:36:54.231+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T11:36:54.231+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/model_train_dag.py", line 16, in train_model
    data = pd.read_csv('../../data/dataset.csv', delimiter=';', decimal=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../data/dataset.csv'
[2024-07-19T11:36:54.238+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_forest_training, task_id=train_model, run_id=scheduled__2024-07-18T00:00:00+00:00, execution_date=20240718T000000, start_date=20240719T113654, end_date=20240719T113654
[2024-07-19T11:36:54.244+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task train_model ([Errno 2] No such file or directory: '../../data/dataset.csv'; 668)
[2024-07-19T11:36:54.268+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-19T11:36:54.284+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T11:36:54.285+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-19T11:50:53.887+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T11:50:53.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T11:50:53.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T11:50:53.912+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-19T11:50:54.105+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-07-18 00:00:00+00:00
[2024-07-19T11:50:54.138+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1045) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T11:50:54.142+0000] {standard_task_runner.py:64} INFO - Started process 1055 to run task
[2024-07-19T11:50:54.141+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_training', 'train_model', 'scheduled__2024-07-18T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/model_train_dag.py', '--cfg-path', '/tmp/tmpd3wuzz3r']
[2024-07-19T11:50:54.147+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask train_model
[2024-07-19T11:50:54.257+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_training.train_model scheduled__2024-07-18T00:00:00+00:00 [running]> on host 6e10856c4017
[2024-07-19T11:50:54.302+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random_forest_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:00+00:00'
[2024-07-19T11:50:54.304+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T11:50:54.314+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T11:50:54.315+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/model_train_dag.py", line 16, in train_model
    data = pd.read_csv('../data/data_clean.csv', delimiter=';', decimal=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../data/data_clean.csv'
[2024-07-19T11:50:54.324+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_forest_training, task_id=train_model, run_id=scheduled__2024-07-18T00:00:00+00:00, execution_date=20240718T000000, start_date=20240719T115053, end_date=20240719T115054
[2024-07-19T11:50:54.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task train_model ([Errno 2] No such file or directory: '../data/data_clean.csv'; 1055)
[2024-07-19T11:50:54.347+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-19T11:50:54.383+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T11:50:54.387+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
